// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9qgeo3sR7TnmhxTE2NnD-O-15brKk-o',
    appId: '1:583686125907:web:06245ef05c5698558649a6',
    messagingSenderId: '583686125907',
    projectId: 'utbk-learning-app',
    authDomain: 'utbk-learning-app.firebaseapp.com',
    storageBucket: 'utbk-learning-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtO525lWQMMiactHKEMqdbEahpn9rgpTw',
    appId: '1:583686125907:android:8a712aa707c20dc88649a6',
    messagingSenderId: '583686125907',
    projectId: 'utbk-learning-app',
    storageBucket: 'utbk-learning-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMU8jEZnSdA8tteyW9mTbq8Ym87nf336c',
    appId: '1:583686125907:ios:e418b3be8573023a8649a6',
    messagingSenderId: '583686125907',
    projectId: 'utbk-learning-app',
    storageBucket: 'utbk-learning-app.appspot.com',
    androidClientId: '583686125907-10b9hailto3lhljdqn05occqbrj6t9hn.apps.googleusercontent.com',
    iosClientId: '583686125907-681qmk3ppgjpal2aikd4aoea5no7121r.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalPorjectEdspert',
  );
}
